# Generated by Django 6.0.5 on 2026-05-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='creditoption',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='tipo',
            field=models.CharField(choices=[('soat', 'SOAT'), ('todo_riesgo', 'Todo Riesgo'), ('personalizado', 'Personalizado')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('ceramico', 'Cerámico 9H'), ('tapiceria', 'Tapicería'), ('polarizado', 'Polarizado'), ('latoneria', 'Latonería y Pintura'), ('mantenimiento', 'Mantenimiento')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], db_index=True, default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='marca',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
    ]
